### ISSUE TITLE
Script error when no shortcut or attachment

### ISSUE THREAD

**Issue by wangwjd** [XUJINKAI/nsx2html#2]
Hi Jinkai,

Your script is wonderful.

I am new to github, can you please fix two tiny issues?
It raises errors when no shortcuts or attachment in notes.

In Line 62, and Line 79, thanks.

	for key in ['id', 'stack', 'tag']:
		if enter['shortcut']: # avoid errors when shortcut is None
			ids_list += enter['shortcut'][key]

	if attachments: # avoid errors when no attachments
		for akey, attach in attachments.items():
			att_src = join_path(tmp_folder, 'file_' + attach['md5'])
			att_dst = join_path(attachment_folder, attach['md5'] + '_' + attach['name'])
			shutil.move(att_src, att_dst)

**Comment by XUJINKAI** [comment]
fixed, thanks your contribution

**Comment by cyorps** [comment]
When I run this script I get following error message:
`Traceback (most recent call last):
  File "nsx2html.py", line 115, in <module>
    render_result(tmp_folder, result_folder)
  File "nsx2html.py", line 88, in render_result
    content = load_folder_content(tmp_folder)
  File "nsx2html.py", line 62, in load_folder_content
    if enter['shortcut']:
KeyError: 'shortcut'`

I tried to run this script in Ubuntu and Windows with the versions 2.7.15 and 3.6.8. Is this the same problem?
